services:
  nebu:
    image: ghcr.io/nickheyer/nebu:${NEBU_CUDA_IMAGE_TAG:-cuda}
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
